on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}